[package]
name = "gtfs-realtime"
description = "Up to date GTFS Realtime specification"
version = "0.4.2"
authors = ["Kyler Chin <kyler@catenarymaps.org>"]
license = "MIT AND Apache-2.0"
repository = "https://github.com/barzamin/gtfs-rt"

edition = "2018"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
prost = "0.11"
prost-derive = "0.11"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
prost-build = "0.11"
